/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateUserDto {
  email: string;
  /** @minLength 8 */
  password: string;
  firstName: string;
  lastName: string;
  phone?: string;
  roleId: string;
  agencyId?: string;
}
