/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface ForgotPasswordDto {
  /** Email du compte pour réinitialisation du mot de passe */
  email: string;
}
