/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceHealthDetailDto } from './serviceHealthDetailDto';

export interface HealthServicesMapDto {
  database: ServiceHealthDetailDto;
  redis: ServiceHealthDetailDto;
  storage: ServiceHealthDetailDto;
}
