/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { HealthResponseDtoStatus } from './healthResponseDtoStatus';
import type { HealthServicesMapDto } from './healthServicesMapDto';

export interface HealthResponseDto {
  status: HealthResponseDtoStatus;
  timestamp: string;
  version: string;
  /** API uptime in seconds */
  uptimeSeconds: number;
  services: HealthServicesMapDto;
}
