/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface LoginDto {
  /** Email de l'utilisateur */
  email: string;
  /**
     * Mot de passe de l'utilisateur
     * @minLength 8
     */
  password: string;
}
