/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface ResetPasswordDto {
  /** Token de réinitialisation sécurisé reçu par email */
  token: string;
  /**
     * Nouveau mot de passe sécurisé
     * @minLength 8
     */
  newPassword: string;
}
