/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceHealthDetailDtoStatus } from './serviceHealthDetailDtoStatus';

export interface ServiceHealthDetailDto {
  status: ServiceHealthDetailDtoStatus;
  /** Response latency in milliseconds */
  latencyMs: number;
  /** Error message if service is down */
  error?: string;
}
