/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ServiceHealthDetailDtoStatus = typeof ServiceHealthDetailDtoStatus[keyof typeof ServiceHealthDetailDtoStatus];


export const ServiceHealthDetailDtoStatus = {
  up: 'up',
  down: 'down',
} as const;
