/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface TokenPairDto {
  /** JWT Access Token court (15m) */
  accessToken: string;
  /** Opaque Refresh Token (7j) */
  refreshToken: string;
  /** Durée de validité en secondes (15 min) */
  expiresIn: number;
  tokenType: string;
}
