/**
 * Generated by orval 🍺
 * Do not edit manually.
 * HES Logistics API
 * Enterprise Multi-Agency Logistics, Parcel Transport, Dispatch, Tracking & Billing REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { UserDtoAgencyId } from './userDtoAgencyId';
import type { UserDtoPhone } from './userDtoPhone';

export interface UserDto {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  /** @nullable */
  phone?: UserDtoPhone;
  role: string;
  /** @nullable */
  agencyId?: UserDtoAgencyId;
  isActive: boolean;
  permissions: string[];
}
